### ISSUE TITLE
GeometryEditor 没找到

### ISSUE THREAD

**Issue by mutou981** [Tencent/tlbs-map-vue#1]
使用 demo 的 https://mapapi.qq.com/web/tlbs-map-vue/components/geometry-editor.html#%E5%9F%BA%E7%A1%80%E7%A4%BA%E4%BE%8B

<img width="770" alt="image" src="https://github.com/user-attachments/assets/099072ee-d400-4177-aa43-caf9c5676506">

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/da132b27-14e4-471b-b3e3-29d11c26d59b">

出现了这个错误，而且无法绘制

**Comment by egbertshendong** [comment]
请提供一下复现代码片段

**Comment by srong123** [comment]
我也遇到了，请问这个怎么解决的

**Comment by srong123** [comment]
已经解决了，在index.html中加上libraries='tools'就可以了
