### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by MarkGor** [Tencent/tlbs-map-vue#6]
### tlbs-map-vue 版本

1.2.0

### 重现步骤

安官網指引：
main.js
`import TlbsMap from 'tlbs-map-vue';`
`Vue.use(TlbsMap);`

yarn run dev
後出現報錯

### 期望结果

沒報錯

### 实际结果

 error  in ./node_modules/tlbs-map-vue/dist/v2.7/index.es.js

Module parse failed: Unexpected token (70:8)
You may need an appropriate loader to handle this file type.
|     return D(async () => {
|       e.apiKey && await F(e.apiKey, e.libraries), t.value && (i = new TMap.Map(t.value, {
|         ...e.options,
|         center: new TMap.LatLng(e.center.lat, e.center.lng),
|         zoom: e.zoom,

 @ ./src/main.js 26:0-35

### 框架版本

vue(2.7)

### Node版本

node(18.19.0)

**Comment by egbertshendong** [comment]
能否提供一下问题复现的demo地址
