### ISSUE TITLE
具体地图方法怎么调用啊

### ISSUE THREAD

**Issue by Bright0810** [Tencent/tlbs-map-vue#8]
![image](https://github.com/user-attachments/assets/64e6db98-b49e-403d-83a9-0efbf37961a0)
文档就写了这么一句话 但是具体怎么调用能给个例子不

**Comment by egbertshendong** [comment]
事件调用方式如下，文档示例代码中有写哈
https://mapapi.qq.com/web/tlbs-map-vue/components/map.html
<img width="1256" alt="Clipboard_Screenshot_1734071655" src="https://github.com/user-attachments/assets/8e47ad26-bb5e-447f-9e82-2875b0cae21d" />

**Comment by Bright0810** [comment]
并不是这个意思 我是想使用 TMap.getCenter()  这样的方法

**Comment by Bright0810** [comment]
> 事件调用方式如下，文档示例代码中有写哈 https://mapapi.qq.com/web/tlbs-map-vue/components/map.html <img alt="Clipboard_Screenshot_1734071655" width="1256" src="https://private-user-images.githubusercontent.com/12248504/395454806-8e47ad26-bb5e-447f-9e82-2875b0cae21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzU4NzAsIm5iZiI6MTczNDA3NTU3MCwicGF0aCI6Ii8xMjI0ODUwNC8zOTU0NTQ4MDYtOGU0N2FkMjYtYmI1ZS00NDdmLTllODItMjg3NWIwY2FlMjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA3MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Y2QyZGZjYjViMWE3YTdkZmUyNzU4MjY2MjM1NzFiYzJjMDE2ZTgwZjczMTQwNjcyM2I0MzlmY2JhODllNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wemG0oNIB5BPlj01Q1GhyM15wDNSaBGpMMr62JLeTjE">

并不是这个意思 我是想使用 TMap.getCenter() 这样的方法

**Comment by egbertshendong** [comment]
> > 事件调用方式如下，文档示例代码中有写哈 https://mapapi.qq.com/web/tlbs-map-vue/components/map.html <img alt="Clipboard_Screenshot_1734071655" width="1256" src="https://private-user-images.githubusercontent.com/12248504/395454806-8e47ad26-bb5e-447f-9e82-2875b0cae21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzU4NzAsIm5iZiI6MTczNDA3NTU3MCwicGF0aCI6Ii8xMjI0ODUwNC8zOTU0NTQ4MDYtOGU0N2FkMjYtYmI1ZS00NDdmLTllODItMjg3NWIwY2FlMjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA3MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Y2QyZGZjYjViMWE3YTdkZmUyNzU4MjY2MjM1NzFiYzJjMDE2ZTgwZjczMTQwNjcyM2I0MzlmY2JhODllNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wemG0oNIB5BPlj01Q1GhyM15wDNSaBGpMMr62JLeTjE">
> 
> 并不是这个意思 我是想使用 TMap.getCenter() 这样的方法
如下面所示，使用ref获得组件引用，然后map.value.map.getCenter()
<img width="833" alt="Clipboard_Screenshot_1734331846" src="https://github.com/user-attachments/assets/d33bf79d-994b-4946-98c4-5f779c9ed9a3" />
<img width="703" alt="Clipboard_Screenshot_1734331748" src="https://github.com/user-attachments/assets/91627117-3df9-4443-905c-8b72bca0fbc1" />

**Comment by Bright0810** [comment]
> > > 事件调用方式如下，文档示例代码中有写哈 https://mapapi.qq.com/web/tlbs-map-vue/components/map.html <img alt="Clipboard_Screenshot_1734071655" width="1256" src="https://private-user-images.githubusercontent.com/12248504/395454806-8e47ad26-bb5e-447f-9e82-2875b0cae21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzU4NzAsIm5iZiI6MTczNDA3NTU3MCwicGF0aCI6Ii8xMjI0ODUwNC8zOTU0NTQ4MDYtOGU0N2FkMjYtYmI1ZS00NDdmLTllODItMjg3NWIwY2FlMjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA3MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Y2QyZGZjYjViMWE3YTdkZmUyNzU4MjY2MjM1NzFiYzJjMDE2ZTgwZjczMTQwNjcyM2I0MzlmY2JhODllNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wemG0oNIB5BPlj01Q1GhyM15wDNSaBGpMMr62JLeTjE">
> > 
> > 
> > 并不是这个意思 我是想使用 TMap.getCenter() 这样的方法
> > 如下面所示，使用ref获得组件引用，然后map.value.map.getCenter()
> 
> <img alt="Clipboard_Screenshot_1734331846" width="833" src="https://private-user-images.githubusercontent.com/12248504/395989691-d33bf79d-994b-4946-98c4-5f779c9ed9a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4MDgsIm5iZiI6MTczNDMzMzUwOCwicGF0aCI6Ii8xMjI0ODUwNC8zOTU5ODk2OTEtZDMzYmY3OWQtOTk0Yi00OTQ2LTk4YzQtNWY3NzljOWVkOWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZWY4M2Y0MTllNDM2OTA4NWMyMDEwMDM2Y2I1MmQwNzk5YTFmZjFjY2U4YTUxMjQ5NjRhOGVhZDEyZjBjY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.65xCWDi2Gjzv40OQxFyZeNoD4Yc75QkPEkh7lWtkI_U"> <img alt="Clipboard_Screenshot_1734331748" width="703" src="https://private-user-images.githubusercontent.com/12248504/395989367-91627117-3df9-4443-905c-8b72bca0fbc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4MDgsIm5iZiI6MTczNDMzMzUwOCwicGF0aCI6Ii8xMjI0ODUwNC8zOTU5ODkzNjctOTE2MjcxMTctM2RmOS00NDQzLTkwNWMtOGI3MmJjYTBmYmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNjIyOTJmY2NjMjhiMjgzZTNmMDMyNzJkNDMwMjFlMzIwYTgwOGJhN2NlY2NiNDZmMGIyODRhM2ZiMTgyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fv17YRyRx72AFJxlR8h8WEUcK3UoqveiysilsZoUc_0">

this.$refs.map.getCenter()    报错  this.$refs.map 没有任何方法····

**Comment by Bright0810** [comment]
> > > > > 事件调用方式如下，文档示例代码中有写哈 https://mapapi.qq.com/web/tlbs-map-vue/components/map.html <img alt="Clipboard_Screenshot_1734071655" width="1256" src="https://private-user-images.githubusercontent.com/12248504/395454806-8e47ad26-bb5e-447f-9e82-2875b0cae21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzU4NzAsIm5iZiI6MTczNDA3NTU3MCwicGF0aCI6Ii8xMjI0ODUwNC8zOTU0NTQ4MDYtOGU0N2FkMjYtYmI1ZS00NDdmLTllODItMjg3NWIwY2FlMjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA3MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Y2QyZGZjYjViMWE3YTdkZmUyNzU4MjY2MjM1NzFiYzJjMDE2ZTgwZjczMTQwNjcyM2I0MzlmY2JhODllNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wemG0oNIB5BPlj01Q1GhyM15wDNSaBGpMMr62JLeTjE">
> > > > 
> > > > 
> > > > 并不是这个意思 我是想使用 TMap.getCenter() 这样的方法
> > > > 如下面所示，使用ref获得组件引用，然后map.value.map.getCenter()
> > > 
> > > 
> > > <img alt="Clipboard_Screenshot_1734331846" width="833" src="https://private-user-images.githubusercontent.com/12248504/395989691-d33bf79d-994b-4946-98c4-5f779c9ed9a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4MDgsIm5iZiI6MTczNDMzMzUwOCwicGF0aCI6Ii8xMjI0ODUwNC8zOTU5ODk2OTEtZDMzYmY3OWQtOTk0Yi00OTQ2LTk4YzQtNWY3NzljOWVkOWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZWY4M2Y0MTllNDM2OTA4NWMyMDEwMDM2Y2I1MmQwNzk5YTFmZjFjY2U4YTUxMjQ5NjRhOGVhZDEyZjBjY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.65xCWDi2Gjzv40OQxFyZeNoD4Yc75QkPEkh7lWtkI_U"> <img alt="Clipboard_Screenshot_1734331748" width="703" src="https://private-user-images.githubusercontent.com/12248504/395989367-91627117-3df9-4443-905c-8b72bca0fbc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4MDgsIm5iZiI6MTczNDMzMzUwOCwicGF0aCI6Ii8xMjI0ODUwNC8zOTU5ODkzNjctOTE2MjcxMTctM2RmOS00NDQzLTkwNWMtOGI3MmJjYTBmYmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNjIyOTJmY2NjMjhiMjgzZTNmMDMyNzJkNDMwMjFlMzIwYTgwOGJhN2NlY2NiNDZmMGIyODRhM2ZiMTgyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fv17YRyRx72AFJxlR8h8WEUcK3UoqveiysilsZoUc_0">
> > 
> > 
> > this.$refs.map.getCenter() 报错 this.$refs.map 没有任何方法····
> 
> 组件导出是一个对象,对象的map属性是地图实例，如果使用this.$refs且ref设置的是map，则通过this.$refs.map.map获取地图实例

this.$refs.map.map  是 null

**Comment by egbertshendong** [comment]
是一开始就要获得地图实例吗，由于组件初始化会异步加载GL地图引擎，所以初始获取实例gl还没加载完会存在null情况，目前有两个办法，一个是通过外链在html就引用gl，<script src="https://map.qq.com/api/gljs?v=1.exp&key=xxx"></script>这样组件不用传api-key，能够直接获取地图实例；第二个办法就是在mount钩子延迟一定时间获取实例。后面我们会增加类似loaded事件来确保获取到map实例

**Comment by Bright0810** [comment]
> 是一开始就要获得地图实例吗，由于组件初始化会异步加载GL地图引擎，所以初始获取实例gl还没加载完会存在null情况，目前有两个办法，一个是通过外链在html就引用gl，<script src="https://map.qq.com/api/gljs?v=1.exp&key=xxx"></script>这样组件不用传api-key，能够直接获取地图实例；第二个办法就是在mount钩子延迟一定时间获取实例。后面我们会增加类似loaded事件来确保获取到map实例

![image](https://github.com/user-attachments/assets/3fe75eb3-6ddb-4252-b36a-aee557110c93)
还是 不行 算了 我看看 不行就用外链 引入吧

**Comment by Swarz** [comment]
<img width="617" height="521" alt="Image" src="https://github.com/user-attachments/assets/9dfbe5a5-03ea-49a2-80d5-84789a562984" />

<img width="750" height="542" alt="Image" src="https://github.com/user-attachments/assets/9558a7ac-538e-4c77-8353-c4946f87cf8c" />

确实提供了，而且map_inited事件也给了，
getCenter可以用

如果使用server，需要libraries传入server，
目前看实例上没有，可以从全局变量TMap上获取
